dnsmasq:
  test_conf: dnsmasq --test
dovecot:
  log: [/var/log/mail.log,/var/log/mail.err]
  needs_exposed_ports: [993]
  category: email
  ignore_if_package_is_not_installed: dovecot-core
crowdsec:
  log: /var/log/crowdsec/crowdsec.log
  category: security
  test_conf: cscli config show >/dev/null 2>&1
crowdsec-firewall-bouncer:
  log: /var/log/crowdsec-firewall-bouncer/crowdsec-firewall-bouncer.log
  category: security
  test_conf: test -f /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
mysql:
  log: [/var/log/mysql.log,/var/log/mysql.err,/var/log/mysql/error.log]
  actual_systemd_service: mariadb
  category: database
  ignore_if_package_is_not_installed: mariadb-server
caddy:
  log: /var/log/caddy
  test_conf: caddy validate --config /etc/caddy/Caddyfile
  needs_exposed_ports: [80, 443]
  category: web
nostrhost-control:
  category: core
nostr-identityd:
  category: admin
nostr-operationsd:
  category: admin
nostr-securityd:
  category: security
nostr-api:
  category: admin
nostrhost-certd:
  category: web
  actual_systemd_service: nostrhost-certd.timer
# Yunohost will dynamically add installed php-fpm services (7.3, 7.4, 8.0, ...) in services.py
#php7.4-fpm:
#  log: /var/log/php7.4-fpm.log
#  test_conf: php-fpm7.4 --test
#  category: web
opendkim:
  category: email
  test_conf: opendkim -n
  ignore_if_package_is_not_installed: opendkim
postfix:
  log: [/var/log/mail.log,/var/log/mail.err]
  actual_systemd_service: postfix@-
  needs_exposed_ports: [25, 587]
  category: email
  ignore_if_package_is_not_installed: postfix
postgresql:
  actual_systemd_service: 'postgresql@15-main'
  category: database
  ignore_if_package_is_not_installed: postgresql-15
redis-server:
  log: /var/log/redis/redis-server.log
  category: database
  ignore_if_package_is_not_installed: redis-server
slapd:
  category: database
  test_conf: slapd -Tt
ssh:
  log: /var/log/auth.log
  test_conf: sshd -t
  needs_exposed_ports: [22]
  category: admin
nftables:
  test_status: nft list chain inet filter input | grep "dport" | grep -q "accept"
  category: security
yunomdns:
  category: mdns
php5-fpm: null
php7.0-fpm: null
php7.3-fpm: null
