"""Native package settings -> YunoHost config panel bridge.

``package.toml`` ``[settings]`` is the declarative, typed source of truth for a
native app's configuration. The resource engine persists it at install
(``settings.ensure``) into ``/var/lib/nostrhost/state/settings/<app>-settings.json``
and injects the values into managed config templates at render time.

This module closes the post-install gap that YunoHost's ``config_panel.toml``
+ ``scripts/config`` covers for scripted apps:

* ``write_config_panel`` generates a YunoHost-compatible ``config_panel.toml``
  and a native ``scripts/config`` in the legacy app-registry entry, so
  webadmin, ``app.config.read`` and ``app.config.set`` (and the underlying
  ConfigPanel machinery) operate on the same typed values the engine persists.
* ``show_values`` is the ``show`` half of that script: the current typed values.
* ``apply_values`` is the ``apply`` half: it validates the submitted values
  against the declared field types, persists them, re-renders the app's
  template-backed config files with the new ``settings`` context, and returns
  per-key ``validation_errors`` for the panel to surface.
* Service restarts are handled by the panel framework (the generated panel
  declares the app's service under ``services``).
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from pathlib import Path
from typing import Any

import yaml

NATIVE_STATE_DIR = Path("/var/lib/nostrhost/state/settings")
NATIVE_APPS_DIR = Path("/etc/yunohost/apps")
NATIVE_PACKAGES_STATE_DIR = Path("/var/lib/nostrhost/state/packages")

# package.toml [settings] field type -> YunoHost config_panel option type.
OPTION_TYPE = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "enum": "select",
}

# Option ids that would collide with a scalar key we emit on the containing
# section. (A sub-table named `type`, `enabled`, ... is legal TOML and parses
# as an option whose own `type` key describes it; only the two keys we emit as
# scalars on a section conflict with an option table name.)
RESERVED_OPTION_KEYS = {"name", "services"}

# Section ids that would collide with scalar keys we emit on the panel
# (`services`) or that the panel/section models treat as container attributes.
RESERVED_SECTION_IDS = {"name", "services", "help", "visible", "optional", "collapsed", "bind", "actions"}

CONFIG_SCRIPT = """#!/bin/bash
set -euo pipefail
# Native NostrHost app config panel (generated by nostrhost settings.ensure).
# Bridges YunoHost's ConfigPanel machinery (config_panel.toml + scripts/config)
# to the native package.toml [settings] state persisted by the resource engine.
# The result is written to $YNH_STDRETURN exactly like a scripted app's
# scripts/config (show -> typed values, apply -> validation_errors or {}).
action="${1:-show}"
PY="${NOSTRHOST_CONFIG_PYTHON:-}"
if [ -z "$PY" ]; then
  if [ -x /opt/nostrhost/venv/bin/python3 ]; then
    PY=/opt/nostrhost/venv/bin/python3
  else
    PY=/usr/bin/python3
  fi
fi
"$PY" -m nostrhost.native_config "$action" > "${YNH_STDRETURN:-/dev/null}"
"""


def _settings_file(app_id: str, state_dir: Path) -> Path:
    return state_dir / f"{_safe_name(app_id)}-settings.json"


def _safe_name(value: str) -> str:
    if not re.fullmatch(r"[a-zA-Z0-9][a-zA-Z0-9_.@:-]*", value):
        raise ValueError(f"unsafe settings identifier: {value!r}")
    return value


def _toml_string(value: Any) -> str:
    return json.dumps(str(value))


def _toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    return _toml_string(value)


def _toml_list(values: list[Any]) -> str:
    return "[" + ", ".join(_toml_string(item) for item in values) + "]"


def _safe_id(value: str) -> str:
    clean = re.sub(r"[^a-z0-9_-]+", "-", str(value).strip().lower()).strip("-")
    if not clean or clean in RESERVED_SECTION_IDS:
        return "main"
    return clean


def read_settings(app_id: str, *, state_dir: Path | None = None) -> dict[str, Any]:
    """Return the persisted native settings record (fields + values)."""
    target = _settings_file(app_id, state_dir or NATIVE_STATE_DIR)
    try:
        data = json.loads(target.read_text(encoding="utf-8"))
    except (FileNotFoundError, OSError, json.JSONDecodeError):
        return {"name": app_id, "fields": {}, "values": {}}
    if not isinstance(data, dict):
        return {"name": app_id, "fields": {}, "values": {}}
    return data


def write_settings(
    app_id: str,
    fields: dict[str, Any],
    values: dict[str, Any],
    *,
    state_dir: Path | None = None,
) -> Path:
    """Persist the native settings record in the engine's JSON shape."""
    base = state_dir or NATIVE_STATE_DIR
    base.mkdir(parents=True, exist_ok=True)
    target = _settings_file(app_id, base)
    temporary = target.with_suffix(".tmp")
    temporary.write_text(
        json.dumps({"name": app_id, "fields": fields, "values": values}, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    os.chmod(temporary, 0o640)
    temporary.replace(target)
    return target


def coerce_value(raw: Any, field: dict[str, Any]) -> Any:
    """Validate/coerce one submitted value against a declared setting field."""
    field_type = field.get("type")
    if raw is None:
        return None
    if isinstance(raw, str):
        raw = raw.strip()
    if field_type == "string":
        return raw
    if field_type == "integer":
        if raw == "":
            return None
        try:
            return int(raw)
        except (TypeError, ValueError) as exc:
            raise ValueError("expected an integer") from exc
    if field_type == "number":
        if raw == "":
            return None
        try:
            return float(raw)
        except (TypeError, ValueError) as exc:
            raise ValueError("expected a number") from exc
    if field_type == "boolean":
        if raw == "":
            return None
        if isinstance(raw, str):
            lowered = raw.lower()
            if lowered in {"true", "1", "yes", "on"}:
                return True
            if lowered in {"false", "0", "no", "off"}:
                return False
        raise ValueError("expected a boolean (true/false)")
    if field_type == "enum":
        if raw == "":
            return None
        choices = field.get("choices") or []
        if raw not in choices:
            raise ValueError(f"must be one of: {', '.join(choices)}")
        return raw
    raise ValueError(f"unsupported setting type {field_type!r}")


def build_config_panel(app_id: str, fields: dict[str, Any]) -> str:
    """Generate the YunoHost ``config_panel.toml`` for a native app.

    Secret fields are skipped (their values come from ``[secrets]`` resources,
    never from the settings store), and fields whose names collide with the
    panel vocabulary are skipped so the generated TOML stays valid. The panel
    declares no ``services``: native services are plain systemd units not in
    YunoHost's ``/etc/yunohost/services.yml`` registry, so the panel
    framework's reload step would reject them; the apply script restarts the
    app's service itself instead.
    """
    sections: dict[str, dict[str, Any]] = {}
    for key, field in fields.items():
        if field.get("secret") or key in RESERVED_OPTION_KEYS:
            continue
        group = field.get("group") or "main"
        section_id = _safe_id(group)
        sections.setdefault(
            section_id,
            {"name": "Settings" if group == "main" else group, "items": []},
        )["items"].append((key, field))

    lines = ["version = 1.0", ""]
    lines.append("[main]")
    lines.append("")
    for section_id, section in sections.items():
        lines.append(f"[main.{section_id}]")
        lines.append(f"name = {_toml_string(section['name'])}")
        lines.append("")
        for key, field in section["items"]:
            lines.append(f"[main.{section_id}.{key}]")
            lines.append(f"type = {_toml_string(OPTION_TYPE[field.get('type', 'string')])}")
            lines.append(f"ask = {_toml_string(field.get('label') or key)}")
            if field.get("description"):
                lines.append(f"help = {_toml_string(field['description'])}")
            lines.append("optional = true")
            if field.get("type") == "enum":
                lines.append(f"choices = {_toml_list(field.get('choices') or [])}")
            if field.get("default") is not None:
                lines.append(f"default = {_toml_value(field['default'])}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_config_panel(
    apps_dir: Path | None,
    app_id: str,
    fields: dict[str, Any],
) -> None:
    """Write config_panel.toml + scripts/config for a native app."""
    if apps_dir is None:
        return
    app_dir = Path(apps_dir) / app_id
    app_dir.mkdir(parents=True, exist_ok=True)
    panel = build_config_panel(app_id, fields)
    target = app_dir / "config_panel.toml"
    temporary = target.with_suffix(".tmp")
    temporary.write_text(panel, encoding="utf-8")
    os.chmod(temporary, 0o644)
    temporary.replace(target)

    script_dir = app_dir / "scripts"
    script_dir.mkdir(parents=True, exist_ok=True)
    script = script_dir / "config"
    temporary_script = script.with_suffix(".tmp")
    temporary_script.write_text(CONFIG_SCRIPT, encoding="utf-8")
    os.chmod(temporary_script, 0o755)
    temporary_script.replace(script)


def remove_config_panel(apps_dir: Path | None, app_id: str) -> None:
    """Drop the generated panel + config script (app removal does the rest)."""
    if apps_dir is None:
        return
    app_dir = Path(apps_dir) / app_id
    (app_dir / "config_panel.toml").unlink(missing_ok=True)
    (app_dir / "scripts" / "config").unlink(missing_ok=True)
    try:
        (app_dir / "scripts").rmdir()
    except OSError:
        pass


def show_values(app_id: str, *, state_dir: Path | None = None) -> dict[str, Any]:
    """The ``show`` half: current typed values for every declared field."""
    state = read_settings(app_id, state_dir=state_dir)
    fields = state.get("fields") or {}
    values = state.get("values") or {}
    result: dict[str, Any] = {}
    for key, field in fields.items():
        if key in values:
            result[key] = values[key]
        elif field.get("default") is not None:
            result[key] = field["default"]
        else:
            result[key] = None
    return result


def apply_values(
    app_id: str,
    env: dict[str, Any],
    *,
    state_dir: Path | None = None,
    root: Path = Path("/"),
    packages_state_dir: Path | None = None,
) -> dict[str, Any]:
    """The ``apply`` half: validate, persist, re-render, and restart.

    ``env`` carries the form values as strings (the ConfigPanel apply env).
    Returns ``{"validation_errors": {key: message}}`` on invalid input, else
    ``{}``. The panel declares no ``services`` (native units are not in
    YunoHost's service registry), so the app's service is reloaded here.
    """
    state = read_settings(app_id, state_dir=state_dir)
    fields = state.get("fields") or {}
    values = dict(state.get("values") or {})
    validation_errors: dict[str, str] = {}
    for key, field in fields.items():
        if key not in env:
            continue
        try:
            values[key] = coerce_value(env[key], field)
        except ValueError as exc:
            validation_errors[key] = str(exc)
    if validation_errors:
        return {"validation_errors": validation_errors}
    write_settings(app_id, fields, values, state_dir=state_dir)
    manifest = _rerender_configs(app_id, values, root=root, packages_state_dir=packages_state_dir)
    _restart_service(app_id, manifest)
    return {}


def _restart_service(app_id: str, manifest: dict[str, Any] | None) -> None:
    service = (manifest or {}).get("service")
    if not isinstance(service, dict):
        return
    name = service.get("name") or app_id
    try:
        subprocess.run(
            ["systemctl", "reload-or-restart", name], check=True, capture_output=True
        )
    except subprocess.CalledProcessError as exc:  # pragma: no cover - systemd env
        raise RuntimeError(f"failed to reload-or-restart {name}: {exc.stderr.decode().strip()}") from exc


def _rerender_configs(
    app_id: str,
    values: dict[str, Any],
    *,
    root: Path = Path("/"),
    packages_state_dir: Path | None = None,
) -> dict[str, Any] | None:
    from .native_providers import ConfigFileProvider, installed_package_manifest
    from .package_engine import Operation

    manifest = installed_package_manifest(app_id, state_dir=packages_state_dir or NATIVE_PACKAGES_STATE_DIR)
    if not manifest:
        return None
    provider = ConfigFileProvider(root=root)
    for name, config in (manifest.get("config") or {}).items():
        if not isinstance(config, dict) or "destination" not in config:
            continue
        args = dict(config)
        args["destination"] = str(config["destination"])
        args["context"] = {**dict(args.get("context") or {}), "settings": values}
        operation = Operation(
            "config.ensure",
            f"{app_id}:config:{name}",
            args,
            reverse="config.remove",
            summary=f"re-render config {config['destination']}",
        )
        provider.apply(operation)
    return manifest


def main(argv: list[str] | None = None) -> int:
    import sys

    args = list(sys.argv[1:] if argv is None else argv)
    action = args[0] if args else "show"
    app_id = os.environ.get("YNH_APP_ID") or ""
    if not app_id:
        basedir = os.environ.get("YNH_APP_BASEDIR") or ""
        if basedir:
            app_id = os.path.basename(os.path.normpath(basedir))
    if not app_id:
        print("nostrhost.native_config: cannot determine app id (set YNH_APP_ID)", file=sys.stderr)
        return 2
    if action == "show":
        sys.stdout.write(yaml.safe_dump(show_values(app_id), default_flow_style=False, sort_keys=False))
        return 0
    if action == "apply":
        result = apply_values(app_id, dict(os.environ))
        sys.stdout.write(yaml.safe_dump(result, default_flow_style=False, sort_keys=False))
        return 0
    print(f"nostrhost.native_config: unknown action {action!r}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())